services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\LockCommandBundle\Command\:
    resource: '../../Command/'
  Tourze\LockCommandBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
